# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plotting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_msgs_pb2 as common__msgs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='plotting.proto',
  package='Nrmk.IndyFramework',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eplotting.proto\x12\x12Nrmk.IndyFramework\x1a\x11\x63ommon_msgs.proto\"\xe3\x02\n\x0cPlottingData\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x10\n\x08op_state\x18\x02 \x01(\r\x12\x14\n\x0cmotion_space\x18\x03 \x01(\r\x12\x12\n\ntraj_state\x18\x04 \x01(\r\x12\x15\n\rtraj_progress\x18\x05 \x01(\r\x12\t\n\x01q\x18\n \x03(\x02\x12\x0c\n\x04qdot\x18\x0b \x03(\x02\x12\r\n\x05qddot\x18\x0c \x03(\x02\x12\n\n\x02qd\x18\r \x03(\x02\x12\r\n\x05qdotd\x18\x0e \x03(\x02\x12\x0e\n\x06qddotd\x18\x0f \x03(\x02\x12\t\n\x01p\x18\x14 \x03(\x02\x12\x0c\n\x04pdot\x18\x15 \x03(\x02\x12\r\n\x05pddot\x18\x16 \x03(\x02\x12\n\n\x02pd\x18\x17 \x03(\x02\x12\r\n\x05pdotd\x18\x18 \x03(\x02\x12\x0e\n\x06pddotd\x18\x19 \x03(\x02\x12\x0b\n\x03tau\x18\x1e \x03(\x02\x12\r\n\x05tauex\x18\x1f \x03(\x02\x12\x0f\n\x07qdotref\x18( \x03(\x02\x12\x0f\n\x07\x65\x64otref\x18) \x03(\x02\x12\x0e\n\x06tauref\x18* \x03(\x02\x32g\n\x11RTPlottingService\x12R\n\x0fGetPlottingData\x12\x19.Nrmk.IndyFramework.Empty\x1a .Nrmk.IndyFramework.PlottingData\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[common__msgs__pb2.DESCRIPTOR,])




_PLOTTINGDATA = _descriptor.Descriptor(
  name='PlottingData',
  full_name='Nrmk.IndyFramework.PlottingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Nrmk.IndyFramework.PlottingData.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_state', full_name='Nrmk.IndyFramework.PlottingData.op_state', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_space', full_name='Nrmk.IndyFramework.PlottingData.motion_space', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traj_state', full_name='Nrmk.IndyFramework.PlottingData.traj_state', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traj_progress', full_name='Nrmk.IndyFramework.PlottingData.traj_progress', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q', full_name='Nrmk.IndyFramework.PlottingData.q', index=5,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qdot', full_name='Nrmk.IndyFramework.PlottingData.qdot', index=6,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qddot', full_name='Nrmk.IndyFramework.PlottingData.qddot', index=7,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd', full_name='Nrmk.IndyFramework.PlottingData.qd', index=8,
      number=13, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qdotd', full_name='Nrmk.IndyFramework.PlottingData.qdotd', index=9,
      number=14, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qddotd', full_name='Nrmk.IndyFramework.PlottingData.qddotd', index=10,
      number=15, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='Nrmk.IndyFramework.PlottingData.p', index=11,
      number=20, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pdot', full_name='Nrmk.IndyFramework.PlottingData.pdot', index=12,
      number=21, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pddot', full_name='Nrmk.IndyFramework.PlottingData.pddot', index=13,
      number=22, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pd', full_name='Nrmk.IndyFramework.PlottingData.pd', index=14,
      number=23, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pdotd', full_name='Nrmk.IndyFramework.PlottingData.pdotd', index=15,
      number=24, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pddotd', full_name='Nrmk.IndyFramework.PlottingData.pddotd', index=16,
      number=25, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau', full_name='Nrmk.IndyFramework.PlottingData.tau', index=17,
      number=30, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tauex', full_name='Nrmk.IndyFramework.PlottingData.tauex', index=18,
      number=31, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qdotref', full_name='Nrmk.IndyFramework.PlottingData.qdotref', index=19,
      number=40, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edotref', full_name='Nrmk.IndyFramework.PlottingData.edotref', index=20,
      number=41, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tauref', full_name='Nrmk.IndyFramework.PlottingData.tauref', index=21,
      number=42, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=413,
)

DESCRIPTOR.message_types_by_name['PlottingData'] = _PLOTTINGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlottingData = _reflection.GeneratedProtocolMessageType('PlottingData', (_message.Message,), {
  'DESCRIPTOR' : _PLOTTINGDATA,
  '__module__' : 'plotting_pb2'
  # @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.PlottingData)
  })
_sym_db.RegisterMessage(PlottingData)



_RTPLOTTINGSERVICE = _descriptor.ServiceDescriptor(
  name='RTPlottingService',
  full_name='Nrmk.IndyFramework.RTPlottingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=415,
  serialized_end=518,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlottingData',
    full_name='Nrmk.IndyFramework.RTPlottingService.GetPlottingData',
    index=0,
    containing_service=None,
    input_type=common__msgs__pb2._EMPTY,
    output_type=_PLOTTINGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RTPLOTTINGSERVICE)

DESCRIPTOR.services_by_name['RTPlottingService'] = _RTPLOTTINGSERVICE

# @@protoc_insertion_point(module_scope)
