# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import teleop_dev_pb2 as teleop__dev__pb2


class TeleOpDeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTeleOpStream = channel.unary_unary(
                '/IndyFramework.Protobuf.TeleDev.TeleOpDevice/StartTeleOpStream',
                request_serializer=teleop__dev__pb2.TeleOpStreamReq.SerializeToString,
                response_deserializer=teleop__dev__pb2.Response.FromString,
                )
        self.StopTeleOpStream = channel.unary_unary(
                '/IndyFramework.Protobuf.TeleDev.TeleOpDevice/StopTeleOpStream',
                request_serializer=teleop__dev__pb2.Empty.SerializeToString,
                response_deserializer=teleop__dev__pb2.Response.FromString,
                )


class TeleOpDeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTeleOpStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTeleOpStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeleOpDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTeleOpStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTeleOpStream,
                    request_deserializer=teleop__dev__pb2.TeleOpStreamReq.FromString,
                    response_serializer=teleop__dev__pb2.Response.SerializeToString,
            ),
            'StopTeleOpStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTeleOpStream,
                    request_deserializer=teleop__dev__pb2.Empty.FromString,
                    response_serializer=teleop__dev__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IndyFramework.Protobuf.TeleDev.TeleOpDevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TeleOpDevice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTeleOpStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IndyFramework.Protobuf.TeleDev.TeleOpDevice/StartTeleOpStream',
            teleop__dev__pb2.TeleOpStreamReq.SerializeToString,
            teleop__dev__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopTeleOpStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IndyFramework.Protobuf.TeleDev.TeleOpDevice/StopTeleOpStream',
            teleop__dev__pb2.Empty.SerializeToString,
            teleop__dev__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
